server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route: /clienta/** -> eureka-clienta service
            - id: authservice-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**          # Match all paths starting with /myclient/
              filters:
                - StripPrefix=1            # Remove /myclient prefix before forwarding

            - id: productservice-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**          # Match all paths starting with /myclient/
              filters:
                - StripPrefix=1

            - id: calculatorservice-route
              uri: lb://CALCULATOR-SERVICE
              predicates:
                - Path=/calculator/**          # Match all paths starting with /myclient/
              filters:
                - StripPrefix=1

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.spring: DEBUG
