server:
  port: 8080

spring:
  application:
    name: consumer
  kafka:
    consumer:
      group-id: sku-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
